### ISSUE TITLE
"it" in example phrase "Asking name" receives "second" tag

### ISSUE THREAD

**Issue by parryc** [alkaitagi/Avzag#81]
Although `lects/phrasebook.json` does not have "it" tagged as `second`. It receives the `second` tag in the interactive phrasebook screen.

![screenshot](https://user-images.githubusercontent.com/1934943/103448449-7bf21980-4c5f-11eb-8716-2ae0bbe15c8d.jpg)

**Comment by alkaitagi** [comment]
Fixed in *Phrasebook* WIP branch.
